# NOT FINISHED
image: node:lts

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - deploy

before_script:
  - docker info

build:
  stage: build
  image: docker:18.03.1
  only:
    - main
  services:
    - docker:dind
  before_script:
    - rm -rf .env
    - cp .env.build .env
    - rm -rf .env.build
  script:
    - ls -la
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/des-labs1/skinwallet-front .
    - docker push registry.gitlab.com/des-labs1/skinwallet-front
deploy:
  stage: deploy
  only:
    - main
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh ${USER}@${HOST} "cd ~/skinwallet && docker-compose pull"
    - ssh ${USER}@${HOST} "cd ~/skinwallet && docker-compose down"
    - ssh ${USER}@${HOST} "cd ~/skinwallet && docker-compose up -d"
