
const LandingInfo = () => {
  return (
        <div className='my-20 text-graySecondary'>
            <h2 className='text-lg tacking-[1.12px] text-white mb-6'>LEARN MORE ABOUT MARKETPLACE AND CS:GO TRADING</h2>
            <p>Let’s start our journey into the CSGO marketplace world by simply telling you what a Skin Marketplace is. Since CSGO items can be traded openly through the Steam Community Market, CSGO skin marketplaces are websites that use those mechanics to provide a faster, more secure and cheaper skin trading experience. They do this by automating trades through bots and allowing you to filter their inventories through various features that the Steam Community Market does not. In this article, we’ll tell you how to buy csgo skins on external marketplaces.</p>
            <div className='mt-14 flex gap-6 flex-col md:flex-row'>
                <div className='flex flex-col gap-5 text-sm w-full md:w-1/2' >
                    <h4 className='text-base text-white'>CSGO Marketplaces and The Economy</h4>
                    <p>To conduct a proper guide to CSGO marketplace trading, we need to briefly get back to the source of all this beautiful mess – Steam. If you want to look at it that way, all trade happens via Steam, even if it’s mediated by third-party sites. The items never leave the Steam system and trade mechanics go down to some sort of automatization of user-to-user trade within Steam Community Market. However, the Steam interface has its limitations that other websites try to mitigate.</p>
                    <p>Having tested the solution on other games before, Valve introduced droppable and tradable skins to Counter-Strike: Global offensive and kickstarted a whole economy around them. To simplify the whole thing, let’s determine two factors at play when it comes to market value. On one hand, you have the rarity – some skins drop ever so, and others barely ever. Usually, the rarer ones are more expensive, but that’s not a golden rule. On the other hand, there’s the aesthetic and personal aspect. Some weapon and knife skins hold up their value quite well because of their uniqueness, but might not just hit the spot for players. If a skin is rare and renowned, or to put it simply – seen well during plays – this is what makes a skin a true treasure.</p>
                    <p>The CSGO Market is a sub-category of the Steam Community Market, an official Steam market of skins, cards, and items from the games that offer such. As a part of the Steam Community Market, the CSGO Market is possibly it’s the biggest sub-category both in the number of items and the amount of money collected there. At the CSGO Steam Market, you can buy CSGO skins, but also all cases, keys, and sticker capsules. All offers are listed by other players, so, in most cases, whenever you buy or sell something, you will be trading with leaving and breathing human being. It is probably the most popular place for skin traders because of the sheer amount of skins, the closeness to the Steam ecosystem and ease of use.</p>
                </div>
                <div className='flex flex-col gap-5 text-sm w-full md:w-1/2'>
                    <h4 className='text-base text-white'>Guide to CSGO Market</h4>
                    <p>Being such an important place Marketplace, CSGO Steam Market is quite easy to use as long as you know certain rules. For starters, you need to fill the requirements to be able to sell and buy items from the CSGO marketplace. The full list of requirements can get quite long, but we will try to name at least some of the most important requirements. For one, your account must be older than 30 days and it has to have at least $5 in the Steam Wallet or bought in games. You also need to enable Steam Guard – a system of security based around your mobile device, thus you will need to download the official Steam app to log in to your Steam account or approve a CSGO skins transaction between two accounts.</p>
                    <p>Now, if you meet all of the skin marketplace CSGO requirements you may begin to buy, sell and generally trade CSGO items. When accessing CSGO Steam Market through the Steam application, you will see your balance, your active listings with the option to see your market history and sell a new CSGO item. You will also see your buy orders – these are usability that lets you define the price of an item that will interest you. This service is used usually if you want a certain skin but you are short on funds. Moreover, whoever fulfills your buy order will have to pay the 15% tax instead of you, the buyer, so take that into your calculations. Going further down, you will see three tabs that you can click between: Popular Items, Newly Listed and Recently Sold. To be honest, only popular items give any good data, especially if you want to track quantity to price relation.</p>
                    <p>On the right side, you will be able to see a search bar. This is where you put your CSGO item queries. You can also search with the use of quite extensively developed advanced search options. That can be helpful in certain situations, for example when you want to see what are the most expensive skins in certain weapon category and grade that aren’t equipped with StatTrak technology.</p>
                    <p>If you click on one of the items listed, its product page will be displayed as well as all CSGO Marketplace related stats like price history, the number of listed pieces and requests to buy as well as the individual listings showcasing wear level, seller and price. Now, if you have funds in your Steam Wallet and your account can trade, you can buy any skin you see on the spot. This will transfer your funds to the seller, add 15% tax for Valve and CSGO developers that you (the buyer) has to pay and automatically send the item to your inventory. An important thing to remember is that all skins bought on or off the CSGO Market are locked for another 8 days from being traded.</p>
                </div>
            </div>
            <div className='border-b border-white/10 my-8' />
            <div className=' flex flex-col md:flex-row gap-6'>
                <div className='flex flex-col gap-5 text-sm w-full md:w-1/2' >
                    <h4 className='text-base text-white'>Csgo Skin Rarity Explained</h4>
                    <p>One of the most important aspects of CSGO skin trading and their price is skin rarity. CSGO skins come in 6 rarity grades that are additionally symbolized by a color. The lowest and most common are the Consumer Grade white skins. Pricewise, these skins are usually extremely cheap or almost worthless. Very rarely they reach up to $20 but never go over $25. Then, slightly less common but still pretty easy to get are Industrial Grade light blue skins. Easy to drop, easy to sell. Don’t go over $50. Next, are Mil-Spec blue skins. These are a bit rarer and, of course, much more expensive. An AUG | Hot Rod Factory New can be sold for $125. Purple Restricted CSGO skins are hard to get and can cost a lot of money. For example, Glock-18 with Fade finish can cost $250 or even more. Classified Pink skins are extremely rare and very expensive. They easily reach $300 or more. Some can even go over $500. The last tier of weapon skins rarity is Covert. These CSGO skins tagged with red color are the most iconic, famous and hard to get skins in the entire game. Example? AWP | Dragon Lore that normally costs around $1500 and a souvenir version of that skin was sold for more than $61,000 in January 2018. If you sell such a CS GO skin you don’t need to worry about money for quite a long time.</p>
                    <p>This means that if you look at our own Marketplace, you will see that the rarer the skin, the more likely its price is to fluctuate. Since the market is very dynamic, rarer skins, particularly those that are no longer easily lootable will see massive price changes, while established common skins will keep their price relatively stable.</p>
                </div>
                <div className='flex flex-col gap-5 text-sm w-full md:w-1/2'>
                    <h4 className='text-base text-white'>Wait… What Marketplace?</h4>
                    <p>When looking for where to buy CSGO skins, you will quickly notice that Steam isn’t the only way to purchase skins. This is where external marketplaces come in. We’ve mentioned them at the start, but here’s a quick overview: These often offer you better prices and better features which allow you to fully customize your inventory to your liking. Some of them even allow you to trade with other users for real cash, with the market being the intermediary, while our own Skinwallet Instant service allows you to sell your skins for cash in bulk.</p>
                    <p>Recently, we’ve launched our very own Skinwallet Market, designed to be the fastest, most secure and most transparent trading platform in the world of CS:GO. We are constantly developing new features, which is why your feedback and your support is invaluable to us. Check it out now, and keep reading to find out how to buy skins quick!</p>
                </div>
            </div>
            <div className='border-b border-white/10 my-8' />
            <div className=' flex flex-col md:flex-row gap-6'>
                <div className='flex flex-col gap-5 text-sm w-full md:w-1/2' >
                    <h4 className='text-base text-white'>How Do You Buy Skins on the Skinwallet Market?</h4>
                    <p>The Skinwallet Market is the best place to buy csgo skins in a simple manner. Start by registering your account, linking it with Steam and confirming your identity. Afterwards, you’re ready to start buying. Browse our market based on what you’re looking for. Do you need a new AK-47 and you’re not sure what you want to buy? No problem, simply check out the AK-47 category through our top menu. Know exactly what you’re looking for? Enter it in the search bar and the skin of your choice will pop up.</p>
                    <p>So you’ve chosen a skin, awesome! Now all you need to do is to purchase it. Top up your balance to buy the skin. Now it’s important to note, that while the skin is assigned to your Skinwallet account automatically, it might not be ready to transfer to your Steam account just yet. If there’s a trade hold on it, you have to wait for it to expire, before withdrawing the skin.</p>
                    <p>To withdraw the skin, simply select it and a Trade Offer will be sent to you by one of our bots. Accept the incoming skin, and voila! You’ve successfully bought your first Skinwallet Market item! Here’s to many more!</p>
                </div>
                <div className='flex flex-col gap-5 text-sm w-full md:w-1/2'>
                    <h4 className='text-base text-white'>What Payment Methods Can You Use on the Skinwallet Market?</h4>
                    <p>You can buy csgo skins with credit card through G2APay. While we know some might be looking to buy csgo skins with PayPal, we believe that VISA, MasterCard and G2APay integration should be enough to easily and securely add funds to your account. We are also planning to add the ability to trade-in skins for Marketplace Currency in the near future, so stay tuned for that.</p>
                    <h4 className='text-base text-white'>Summary</h4>
                    <p>When it comes to CSGO skins, buying the Skinwallet Market CSGO is a stable, safe and regulated solution that will allow any new users to buy the skins of choice with no hustle. It’s understandable that many safety gates and the interface might not be the most comfortable option; however, the process is easy to realize and guarantees you probably best access to the items you’re looking for. You’re, of course, welcome to share any thoughts about Skinwallet Market usability in the comments and we’ll do our best to answer meaningfully.</p>
                </div>
            </div>
    </div>
  )
}

export default LandingInfo
